name = "Workshop Wizardry"
author = "Andrew"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8984f2f5236899a75296609a081ca7555bfc659fcfdb0686318cd92447b4dc75"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20-pre1"]
datapack-folder = "config/openloader/data"
