name = "Workshop Wizardry"
author = "Andrew"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc6792af5e0125c5982e1ecac3b62e7bf861f9068a39d597bb29d59369b37220"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20-pre1"]
datapack-folder = "config/openloader/data"
