name = "Workshop Wizardry"
author = "Andrew"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf9c6cd6a3d5bdc67bce44b09047df54ba2dff00acec7f12571a74fc7ed34203"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20-pre1"]
datapack-folder = "config/openloader/data"
