name = "Workshop Wizardry"
author = "Andrew"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "796fb20ded15139b240c9ca183f5e4de1805609a93bbcf2613718b9e43d34d10"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20-pre1"]
datapack-folder = "config/openloader/data"
