name = "Workshop Wizardry"
author = "Andrew"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be2e90d1dd25b2473c515234e64e4a2a6c8f05efddea24cff8aa3fdd7d2606ea"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20-pre1"]
datapack-folder = "config/openloader/data"
